# Generated by Django 3.2.6 on 2021-08-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FilePathField(default='', path='static/media/services'),
        ),
    ]
