# Generated by Django 3.2.6 on 2021-08-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='', upload_to='static/media/services'),
        ),
    ]
